### ISSUE TITLE
Leaving attack URL blank if programatically specifing attack URL

### ISSUE THREAD

**Issue by petermartin2002** [jenkinsci/zaproxy-plugin#12]
Hi,

I am playing about with the plugin for Zap Proxy as I have implemented a java program that will programmatically use the proxy api to spider and scan a website. 

What I want to use the plug in is start the zap proxy on my node if it is not already running.  

I could do this by running a .bat but I thought I would play with the plugin first. 

However when I run the job on Jenkins I get the following error:
zapProgram = C:\Program Files (x86)\OWASP\Zed Attack Proxy
ERROR: java.lang.IllegalArgumentException: targetURL is missing
	at fr.novia.zaproxyplugin.ZAProxy.checkParams(ZAProxy.java:582)
	at fr.novia.zaproxyplugin.ZAProxy.startZAP(ZAProxy.java:613)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.prebuild(ZAProxyBuilder.java:140)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:834)
	at hudson.model.AbstractBuild$AbstractBuildExecution.preBuild(AbstractBuild.java:829)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:664)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:531)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:381)

Now I know that it may seem that the plugin makes my code kind of obsolete (lucky me).  However,  I want to know can I use it the way I was intending initially. Ie use it to start a pre installed instance of Zap Proxy, set it up deploy my code and record the html and xml report on completion?

**Comment by thilina27** [comment]
you get this error coz you didnt put a url to be scanned/spider. 
You need to do is use the plugin only to start zap ?
 i dont think this plugin can use for that purpose. 
check this plugin i think it will be dose what you need. 

https://wiki.jenkins-ci.org/display/JENKINS/Zapper+Plugin

**Comment by petermartin2002** [comment]
I will play with this plugin thanks
