### ISSUE TITLE
"No Implementor" on AJAXSpider crawl

### ISSUE THREAD

**Issue by yarafatin** [jenkinsci/zaproxy-plugin#19]
I setup the plugin and used ZAP 2.4.3 as pre-installed. I just used the default values in the job.
I am using "ZAProxy is already Installed" with an environment variable.
Another thing I noted is that the "Choose policy to use" as empty list.

When I run the job, I get the following exception . Is this plugin compatible with 2.4.3?
```
URL http://xxx.xxx.xxx.xxx/yo/login.html added to Context [2]
URL exluded from context : http://xxx.xxx.xxx.xxx/yo/config.html
SCANMOD : NOT_AUTHENTICATED
Spider the site [http://xxx.xxx.xxx.xxx/yo/login.html]
15587 [Thread-3] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Starting spidering scan on SpiderApi-0 at Thu Jan 21 11:16:35 EST 2016
15589 [Thread-3] INFO org.zaproxy.zap.spider.Spider  - Spider initializing...
Status spider = 0%
Alerts number = 		ApiResponseElement numberOfAlerts = 0

15692 [Thread-3] INFO org.zaproxy.zap.spider.Spider  - Starting spider...
15732 [Thread-3] INFO org.zaproxy.zap.spider.Spider  - Adding seed for spider: http://xxx.xxx.xxx.xxx/yo/login.html
15739 [Thread-3] INFO org.zaproxy.zap.spider.Spider  - Adding seed for spider: http://dav.dev.uspto.gov/robots.txt
15742 [Thread-3] INFO org.zaproxy.zap.spider.Spider  - Adding seed for spider: http://dav.dev.uspto.gov/sitemap.xml
16077 [pool-1-thread-2] INFO org.zaproxy.zap.spider.Spider  - Spidering process is complete. Shutting down...
16084 [Thread-5] INFO org.zaproxy.zap.extension.spider.SpiderThread  - Spider scanning complete: true
Ajax Spider the site [http://xxx.xxx.xxx.xxx/yo/login.html]
16740 [ZAP-ProxyThread-10] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
No Implementor (no_implementor)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
ERROR: org.zaproxy.clientapi.core.ClientApiException: No Implementor
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(Unknown Source)
	at org.zaproxy.clientapi.core.ClientApi.callApi(Unknown Source)
	at org.zaproxy.clientapi.gen.AjaxSpider.scan(Unknown Source)
	at fr.novia.zaproxyplugin.ZAProxy.ajaxSpiderURL(ZAProxy.java:1371)
	at fr.novia.zaproxyplugin.ZAProxy.executeZAP(ZAProxy.java:959)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:368)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:354)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2719)
	at hudson.remoting.UserRequest.perform(UserRequest.java:120)
	at hudson.remoting.UserRequest.perform(UserRequest.java:48)
	at hudson.remoting.Request$2.run(Request.java:326)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)

Shutdown ZAProxy
Build step 'Execute ZAProxy' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by thc202** [comment]
That error means that the AJAX Spider add-on is not installed in ZAP (or was not initialised).

Are you sure that the ZAP package that you are using bundles that add-on? For example, Core does not while Standard does. [1]


[1] https://github.com/zaproxy/zaproxy/wiki/Downloads

**Comment by yarafatin** [comment]
You are right. Core was installed and not the standard. Thank you for your help!

**Comment by Mouheb22** [comment]
hello @thc202 
i'm a new user of zap and i have the same problem here, i have "ZAP 2.4.3" installed by custom tools can you tell me how to install ajax spider add-on.

**Comment by yarafatin** [comment]
In the zap download page there are two categories standard and core. Core doesn't contain ajax spider add on. You need to use the standard package with the custom tool.

**Comment by Mouheb22** [comment]
hi @yarafatin thnx for responding me, 
so i'm trying to download ZAP 2.4.3 standard with custom tools and it fails, here is my console output:

D�marr� par l'utilisateur anonymous
Building in workspace C:\Program Files (x86)\Jenkins\jobs\Test\workspace
------- START Replace environment variables -------
ReportName : reportsZAP/report
------- END Replace environment variables -------
Perform ZAProxy
Unpacking https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Windows.exe to C:\Program Files (x86)\Jenkins\tools\com.cloudbees.jenkins.plugins.customtools.CustomTool\ZAP_2.4.3_Standard on Jenkins
ERROR: java.io.IOException: Failed to install https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Windows.exe to C:\Program Files (x86)\Jenkins\tools\com.cloudbees.jenkins.plugins.customtools.CustomTool\ZAP_2.4.3_Standard
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:832)
	at hudson.tools.ZipExtractionInstaller.performInstallation(ZipExtractionInstaller.java:79)
	at hudson.tools.InstallerTranslator.getToolHome(InstallerTranslator.java:68)
	at hudson.tools.ToolLocationNodeProperty.getToolHome(ToolLocationNodeProperty.java:108)
	at hudson.tools.ToolInstallation.translateFor(ToolInstallation.java:206)
	at com.cloudbees.jenkins.plugins.customtools.CustomTool.forNode(CustomTool.java:154)
	at com.cloudbees.jenkins.plugins.customtools.CustomTool.forNode(CustomTool.java:59)
	at fr.novia.zaproxyplugin.ZAProxy.retrieveZapHomeWithToolInstall(ZAProxy.java:744)
	at fr.novia.zaproxyplugin.ZAProxy.checkParams(ZAProxy.java:802)
	at fr.novia.zaproxyplugin.ZAProxy.startZAP(ZAProxy.java:861)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.perform(ZAProxyBuilder.java:189)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: Failed to unpack https://github.com/zaproxy/zaproxy/releases/download/2.4.3/ZAP_2.4.3_Windows.exe (8192 bytes read of total 75764259)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:826)
	... 19 more
Caused by: java.io.IOException: Failed to extract input stream
	at hudson.FilePath.readFromTar(FilePath.java:2300)
	at hudson.FilePath.access$400(FilePath.java:190)
	at hudson.FilePath$10.invoke(FilePath.java:720)
	at hudson.FilePath$10.invoke(FilePath.java:718)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at hudson.FilePath.untarFrom(FilePath.java:718)
	at hudson.FilePath.installIfNecessaryFrom(FilePath.java:824)
	... 19 more
Caused by: java.io.IOException: incorrect header check
	at com.jcraft.jzlib.InflaterInputStream.read(InflaterInputStream.java:112)
	at org.apache.commons.compress.utils.IOUtils.readFully(IOUtils.java:160)
	at org.apache.commons.compress.utils.IOUtils.readFully(IOUtils.java:134)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.readRecord(TarArchiveInputStream.java:419)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getRecord(TarArchiveInputStream.java:388)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.getNextTarEntry(TarArchiveInputStream.java:269)
	at hudson.FilePath.readFromTar(FilePath.java:2278)
	... 26 more

Build step 'Execute ZAProxy' marked build as failure
Finished: FAILURE

**Comment by thc202** [comment]
It seems that it requires a compressed archive, try with the standard "Cross platform" package instead.

**Comment by Mouheb22** [comment]
hi @thc202 , yeah i did that and the build succeed thnx for helping but there's some problems with the ajax spider look @ my console output :  

Ajax Spider the site [http://********************]
10066 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Running crawljax targeting http://********************
10066 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Starting proxy...
10068 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Proxy started, listening at port [52974].
Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

11064 [Thread-4] WARN com.crawljax.core.plugin.Plugins  - No plugins loaded. There will be no output
Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

Status spider = running
Alerts number = 		ApiResponseElement numberOfAlerts = 0

32203 [pool-1-thread-2] INFO com.crawljax.browser.WebDriverBackedEmbeddedBrowser  - Closing the browser...
32205 [Thread-4] INFO com.crawljax.core.CrawlController  - Received shutdown notice. Reason is Exausted
32448 [pool-1-thread-2] WARN org.openqa.selenium.os.ProcessUtils  - Process refused to die after 10 seconds, and couldn't taskkill it
org.openqa.selenium.WebDriverException: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '*****PC', ip: ' ***.***.***.*** ', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:123)
	at org.openqa.selenium.os.CommandLine.execute(CommandLine.java:116)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:173)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:259)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:204)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:377)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:467)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.close(WebDriverBackedEmbeddedBrowser.java:328)
	at com.crawljax.core.Crawler.close(Crawler.java:94)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:50)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.commons.exec.DefaultExecuteResultHandler.waitFor(DefaultExecuteResultHandler.java:121)
	at org.openqa.selenium.os.UnixProcess.waitFor(UnixProcess.java:139)
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:121)
	... 21 more
32452 [pool-1-thread-2] ERROR com.crawljax.core.CrawlTaskConsumer  - Unexpected error Process refused to die after 10 seconds, and couldn't taskkill it: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '*******-PC', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: *******-PC', ip:  '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:142)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:259)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:204)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:377)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:323)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:467)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.close(WebDriverBackedEmbeddedBrowser.java:328)
	at com.crawljax.core.Crawler.close(Crawler.java:94)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:50)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '*********-PC', ip:  '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:123)
	at org.openqa.selenium.os.CommandLine.execute(CommandLine.java:116)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:173)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	... 18 more
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.commons.exec.DefaultExecuteResultHandler.waitFor(DefaultExecuteResultHandler.java:121)
	at org.openqa.selenium.os.UnixProcess.waitFor(UnixProcess.java:139)
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:121)
	... 21 more
32453 [Thread-4] INFO com.crawljax.core.CrawlController  - Shutdown process complete
32453 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Stopping proxy...
32554 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Proxy stopped.
32554 [Thread-4] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Finished crawljax targeting http://**********************
Skip scanning the site [http://**********************/]
Skipped creating jiras
Save session to [C:\Program Files (x86)\Jenkins\jobs\Test\workspace\ZAPsession1]
32923 [ZAP-ProxyThread-35] INFO org.parosproxy.paros.control.Control  - Save Session
33132 [Thread-7] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start
33315 [Thread-7] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Database closed
33485 [Thread-7] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
33488 [Thread-7] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end
Total alerts = 		ApiResponseElement numberOfAlerts = 0

Total messages = 		ApiResponseElement numberOfMessages = 0

Shutdown ZAProxy
Finished: SUCCESS

**Comment by thc202** [comment]
That's most likely because of older version of Selenium add-on. Try adding the following command line argument to "Add ZAProxy command line option", `-addoninstall`, as option, and `selenium`, as value, which updates it to latest version.

**Comment by Mouheb22** [comment]
hi @thc202  i have 3 warning now


*******************************
WARN org.zaproxy.zap.extension.globalexcludeurl.ExtensionGlobalExcludeURL  - GlobalExcludeURL.optionsLoaded()

********************************

7692 [Thread-6] WARN com.crawljax.core.plugin.Plugins  - No plugins loaded. There will be no output

********************************

237159 [pool-1-thread-2] WARN org.openqa.selenium.os.ProcessUtils  - Process refused to die after 10 seconds, and couldn't taskkill it
org.openqa.selenium.WebDriverException: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '***********-PC', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:125)
	at org.openqa.selenium.os.CommandLine.execute(CommandLine.java:118)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:179)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:246)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:194)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:364)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:529)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.close(WebDriverBackedEmbeddedBrowser.java:328)
	at com.crawljax.core.Crawler.close(Crawler.java:94)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:50)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.commons.exec.DefaultExecuteResultHandler.waitFor(DefaultExecuteResultHandler.java:121)
	at org.openqa.selenium.os.UnixProcess.waitFor(UnixProcess.java:139)
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:123)
	... 21 more
237165 [pool-1-thread-2] ERROR com.crawljax.core.CrawlTaskConsumer  - Unexpected error Process refused to die after 10 seconds, and couldn't taskkill it: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '*******-PC', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '**********-PC', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:142)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:247)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$2(UnixProcess.java:246)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:125)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:155)
	at org.openqa.selenium.firefox.FirefoxBinary.quit(FirefoxBinary.java:246)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.quit(NewProfileExtensionConnection.java:194)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.quit(FirefoxDriver.java:364)
	at org.openqa.selenium.firefox.FirefoxDriver.stopClient(FirefoxDriver.java:310)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:529)
	at com.crawljax.browser.WebDriverBackedEmbeddedBrowser.close(WebDriverBackedEmbeddedBrowser.java:328)
	at com.crawljax.core.Crawler.close(Crawler.java:94)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:50)
	at com.crawljax.core.CrawlTaskConsumer.call(CrawlTaskConsumer.java:16)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.openqa.selenium.WebDriverException: java.lang.InterruptedException: sleep interrupted
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: **********-PC', ip: '***.***.***.***', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_77'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:125)
	at org.openqa.selenium.os.CommandLine.execute(CommandLine.java:118)
	at org.openqa.selenium.os.WindowsUtils.killPID(WindowsUtils.java:179)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:138)
	... 18 more
Caused by: java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
	at org.apache.commons.exec.DefaultExecuteResultHandler.waitFor(DefaultExecuteResultHandler.java:121)
	at org.openqa.selenium.os.UnixProcess.waitFor(UnixProcess.java:139)
	at org.openqa.selenium.os.CommandLine.waitFor(CommandLine.java:123)
	... 21 more
237167 [Thread-6] INFO com.crawljax.core.CrawlController  - Shutdown process complete
237167 [Thread-6] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Stopping proxy...
237267 [Thread-6] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Proxy stopped.
237267 [Thread-6] INFO org.zaproxy.zap.extension.spiderAjax.SpiderThread  - Finished crawljax targeting http://****************/

Skip scanning the site [http://****************/]
Skipped creating jiras
Save session to [C:\Program Files (x86)\Jenkins\jobs\Test\workspace\ZAPsession1]
238728 [ZAP-ProxyThread-287] INFO org.parosproxy.paros.control.Control  - Save Session
238812 [Thread-8] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache commit start

239159 [Thread-8] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - Database closed
239309 [Thread-8] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open start
239312 [Thread-8] INFO hsqldb.db.HSQLDB379AF3DEBD.ENGINE  - dataFileCache open end

Total alerts = 		ApiResponseElement numberOfAlerts = 162

Total messages = 		ApiResponseElement numberOfMessages = 188

**Comment by thc202** [comment]
The first two warnings can be ignored, the last one, it depends, was the browser closed?
Did the AJAX spider run as expected?
