### ISSUE TITLE
ZaProxy plugin fails

### ISSUE THREAD

**Issue by molsky** [jenkinsci/zaproxy-plugin#27]
After upgraded plugin from 1.1.7 to 1.2.0 the execution fails when trying to launch ZAProxy.
```
zapProgram = /opt/jenkins-data/tools/com.cloudbees.jenkins.plugins.customtools.CustomTool/ZAProxy_2.4.3/ZAP_2.4.3
targetURL = www.example.com
zapProxyHost = localhost
zapProxyPort = 8090
ERROR: java.lang.NullPointerException
	at fr.novia.zaproxyplugin.ZAProxy.checkParams(ZAProxy.java:772)
	at fr.novia.zaproxyplugin.ZAProxy.startZAP(ZAProxy.java:809)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.perform(ZAProxyBuilder.java:194)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
	at hudson.model.Build$BuildExecution.build(Build.java:199)
	at hudson.model.Build$BuildExecution.doRun(Build.java:160)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
	at hudson.model.Run.execute(Run.java:1759)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)

Build step 'Execute ZAProxy' marked build as failure
```
Tried with minimal setup (non-authenticated, no excludes, spider & scan url, 
Jenkins ver. 1.590
java version "1.7.0_45"

**Comment by thilina27** [comment]
Hi

Its been fixed in the https://github.com/jenkinsci/zaproxy-plugin/pull/24

But haven't merged yet. It will be merge and released soon. 

Until that you can merge it to your fork and build and manually install plugin.

**Comment by ludovicRoucoux** [comment]
PR is merged.
