### ISSUE TITLE
Authentication Script: Zest failure

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#31]
Hi,

I have received "Error: Unable to load Script Based Authentication method. The script dynauth.zst contains errors", happens when ever i use a ZEST script file as an authentication method.

Use case
Use a recorded ".zst" script as a Script based Authentication Method

Note: ZAProxy version is 2.5
 
Regards,
mabdelmoez

P.S: Blow is the full error log (and exception stack trace), retrieved from Jenkins Console Log:

SCANMOD : AUTHENTICATED
Setting up Authentication
Setting Script based authentication configuration as: scriptName=dynauth.zst
8896 [ZAP-ProxyThread-5] INFO org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType  - Loaded script for API:dynauth.zst
9045 [ZAP-ProxyThread-5] ERROR org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType  - Unable to load Script Based Authentication method. The script dynauth.zst contains errors.
9046 [ZAP-ProxyThread-5] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
An error has occurred when loading the provided script (bad_script_format) : missing_parameter
	at org.zaproxy.zap.authentication.ScriptBasedAuthenticationMethodType$1.handleAction(Unknown Source)
	at org.zaproxy.zap.extension.authentication.AuthenticationAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR: org.zaproxy.clientapi.core.ClientApiException: An error has occurred when loading the provided script
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:32)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:290)
	at org.zaproxy.clientapi.gen.Authentication.setAuthenticationMethod(Authentication.java:85)
	at fr.novia.zaproxyplugin.ZAProxy.setUpScriptBasedAuthenticationMethod(ZAProxy.java:1581)
	at fr.novia.zaproxyplugin.ZAProxy.setUpAuthentication(ZAProxy.java:1684)
	at fr.novia.zaproxyplugin.ZAProxy.executeZAP(ZAProxy.java:1230)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:395)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:381)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.perform(ZAProxyBuilder.java:200)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)

Shutdown ZAProxy
Build step 'Execute ZAProxy' marked build as failure
Finished: FAILURE

**Comment by memarques** [comment]
Hi, I'm having the exact same issue. Any plans on fixing this?
Thanks!

**Comment by mabdelmoez** [comment]
Fix for the zaproxy-plugin 
https://github.com/jenkinsci/zaproxy-plugin/pull/33

**Comment by thc202** [comment]
@mabdelmoez and @memarques does the script that you are using have any parameters?

There's an issue in Zest add-on that caused the parameters LoginURL/Method to be required, always. [1]
A new version should be released soon which would fix this bug (if no parameter is really required by the scripts).

Also, the API error message was changed to provide the actual problem (which was missing parameters). [2]

[1] zaproxy/zaproxy#2734
[2] zaproxy/zaproxy#2737

**Comment by mabdelmoez** [comment]
@thc202  Yes I do pass the LoginURL for now, and re. any other parameters i need to pass currently, they are recorded. 

Anyway, i am thinking of amending my commit to enable the users to insert the parameters they wish so that it opens up a wide range of possibilities in terms of parameters to pass along with the authentication script ? But the question then is, should i limit them to be 2 or more ? And does ZAP accept as many parameters (if any) so that before i change the commit, it would be on the same page with ZAP's API & ZAP's Core's functionality.

btw. this would be a good feature, ex. for second factor authentication tokens as params.

**Comment by memarques** [comment]
Well, when using zap UI I pass 3 parameters, LoginUrl, username and password. On jenkins I hardcoded everything so in the end I wasn't passing none of them.

**Comment by mabdelmoez** [comment]
Pull request changed https://github.com/jenkinsci/zaproxy-plugin/pull/33. Now it is possible for the user to define his scriptBasedParameters and values.

**Comment by mabdelmoez** [comment]
Resolved in pull https://github.com/jenkinsci/zaproxy-plugin/pull/40, followed by https://github.com/jenkinsci/zaproxy-plugin/pull/41 
Currently doing tests for the pulls.
