### ISSUE TITLE
contextName = "context1"; leads to incorrect API calls within the session

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#32]
Hi,

Here is an issue that i have faced using the plugin on a loaded session:

contextName is always a constant -> "context1". Therefore, In case of, there are two contexts using the same name (For example, a second scan/run on a loaded session), that leads to using a-non-unique contextName -> "context1" as a parameter to ZAP API calls. Call example: "zapClientAPI.context.includeInContext(API_KEY,contextName,contextURL);", that results in, The target URL not being included in the intended context within that session, but the very first context with the name "context1".

Note: ZAP version is 2.5.
If you need more info, please let me know.

P.S: Exception stack traced found in Jenkins Console log:

The provided url is not in the required context (url_not_in_context) : url
	at org.zaproxy.zap.extension.spider.SpiderAPI.scanURL(Unknown Source)
	at org.zaproxy.zap.extension.spider.SpiderAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR: org.zaproxy.clientapi.core.ClientApiException: The provided url is not in the required context
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:32)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:290)
	at org.zaproxy.clientapi.gen.Spider.scanAsUser(Spider.java:239)
	at fr.novia.zaproxyplugin.ZAProxy.spiderURLAsUser(ZAProxy.java:1834)
	at fr.novia.zaproxyplugin.ZAProxy.executeZAP(ZAProxy.java:1334)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:395)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:381)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.perform(ZAProxyBuilder.java:200)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)

Regards,
mabdelmoez

**Comment by mabdelmoez** [comment]
https://github.com/zaproxy/zaproxy/issues/2741

**Comment by JordanGS** [comment]
@mabdelmoez Resolved in pull request #41, feel free to re-open or adjust your pull request to add any additional features you may like. I have since made context name a required field.
