### ISSUE TITLE
 ZAProxy v2.5 - Add User - Inconsistent names of parameters between API and The Plugin

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#37]
Hi,

The plugin passes the parameters as lower case "username" & "password", however the API expects them to be "Username" & "Password".

ZAProxy version 2.5.

P.S. Please find below the stack trace fetched from the jenkins' console log.
ERROR: org.zaproxy.clientapi.core.ClientApiException: Missing Parameter
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(Unknown Source)
	at org.zaproxy.clientapi.core.ClientApi.callApi(Unknown Source)
	at org.zaproxy.clientapi.gen.Users.setAuthenticationCredentials(Unknown Source)
	at fr.novia.zaproxyplugin.ZAProxy.setUpUser(ZAProxy.java:1607)
	at fr.novia.zaproxyplugin.ZAProxy.setUpAuthentication(ZAProxy.java:1672)
	at fr.novia.zaproxyplugin.ZAProxy.executeZAP(ZAProxy.java:1241)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:395)
	at fr.novia.zaproxyplugin.ZAProxyBuilder$ZAProxyCallable.invoke(ZAProxyBuilder.java:381)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at fr.novia.zaproxyplugin.ZAProxyBuilder.perform(ZAProxyBuilder.java:200)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

**4416 [ZAP-ProxyThread-9] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:**
**Missing Parameter (missing_parameter) : Username**
	at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(Unknown Source)
	at org.zaproxy.zap.authentication.GenericAuthenticationCredentials$1.handleAction(Unknown Source)
	at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by JordanGS** [comment]
@mabdelmoez Is this for script based authentication or?

**Comment by mabdelmoez** [comment]
Yes, if we plan to use ZAP 2.5 for this release. Then we need to address that one. I think we should use the latest ZAP, what do you think ?

**Comment by JordanGS** [comment]
Then it's been addressed and i'll close this issue. Form based has parameter fields and script based was addressed by you. Resolved in #41 or a subsequent pull by you.
