### ISSUE TITLE
Bug - After upgrade to Client API 1.0: zapClientAPI.users.setAuthenticationCredentials expects semi camel case parameters (scriptBasedAuthentication)

### ISSUE THREAD

**Issue by mabdelmoez** [jenkinsci/zaproxy-plugin#43]
After upgrade to Client API 1.0: zapClientAPI.users.setAuthenticationCredentials expects semi camel case parameters. Only for script based authentication, and probably for ZEST only.

Otherwise the following exception appears
3914 [ZAP-ProxyThread-9] WARN org.zaproxy.zap.extension.api.API  - ApiException while handling API request:
Missing Parameter (missing_parameter) : Username
	at org.zaproxy.zap.utils.ApiUtils.getNonEmptyStringParam(Unknown Source)
	at org.zaproxy.zap.authentication.GenericAuthenticationCredentials$1.handleAction(Unknown Source)
	at org.zaproxy.zap.extension.users.UsersAPI.handleApiAction(Unknown Source)
	at org.zaproxy.zap.extension.api.API.handleApiRequest(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.processHttp(Unknown Source)
	at org.parosproxy.paros.core.proxy.ProxyThread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR: org.zaproxy.clientapi.core.ClientApiException: Missing Parameter
	at org.zaproxy.clientapi.core.ApiResponseFactory.getResponse(ApiResponseFactory.java:32)
	at org.zaproxy.clientapi.core.ClientApi.callApi(ClientApi.java:290)
	at org.zaproxy.clientapi.gen.Users.setAuthenticationCredentials(Users.java:134)
	at com.github.jenkinsci.zaproxyplugin.ZAPDriver.setUpUser(ZAPDriver.java:1288)
	at com.github.jenkinsci.zaproxyplugin.ZAPDriver.setUpAuthentication(ZAPDriver.java:1394)
	at com.github.jenkinsci.zaproxyplugin.ZAPDriver.executeZAP(ZAPDriver.java:763)
	at com.github.jenkinsci.zaproxyplugin.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:336)
	at com.github.jenkinsci.zaproxyplugin.ZAPBuilder$ZAPDriverCallable.invoke(ZAPBuilder.java:324)
	at hudson.FilePath.act(FilePath.java:1018)
	at hudson.FilePath.act(FilePath.java:996)
	at com.github.jenkinsci.zaproxyplugin.ZAPBuilder.perform(ZAPBuilder.java:217)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1720)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)

Fix was added, currently being pushed.

**Comment by mabdelmoez** [comment]
Addressed in https://github.com/jenkinsci/zaproxy-plugin/pull/44
